twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        # Obtain it from the .env file:
        app_environment: '%env(APP_ENV)%'

when@test:
    twig:
        strict_variables: true
