version: '3'

services:
  database:
    image: mariadb:10.6.5-focal
    environment:
      MARIADB_USER: document
      MARIADB_PASSWORD: root
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: false
      MARIADB_ROOT_PASSWORD: root
      MARIADB_RANDOM_ROOT_PASSWORD: no
      MARIADB_DATABASE: docroot
    ports: [3306]
